#!/usr/bin/env python3
"""
VeriFireWall - Security Analyst Explainability Telemetry Parser
--------------------------------------------------------------
Parses security logs generated by VeriFireWall (WaapResultJson format)
and produces clear, human-readable visual explainability summaries
for security analysts and hackathon judges.
"""

import sys
import json
import argparse
from typing import Dict, Any

def format_explanation(event: Dict[str, Any]) -> str:
    data = event.get("data", {})
    res = event.get("res", {})
    transaction = data.get("transaction", {})
    request = data.get("request", {})
    
    time_str = transaction.get("time", "N/A")
    support_id = transaction.get("support_id", "N/A")
    remote_addr = transaction.get("remote_address", "N/A")
    
    method = request.get("method", "N/A")
    uri = request.get("uri", "N/A")
    
    param_name = res.get("param_name", "N/A")
    param_location = res.get("param_location", "N/A")
    line = res.get("line", "")
    score = res.get("score", 0.0)
    keyword_matches = res.get("keyword_matches", [])
    ntags = res.get("ntags", {})
    scores_array = res.get("scores_array", [])
    
    output = []
    output.append("=" * 70)
    output.append(" 🔥 VeriFireWall Security Anomaly Explainability Report")
    output.append("=" * 70)
    output.append(f" 🕒 Timestamp:         {time_str}")
    output.append(f" 🆔 Support/Tx ID:      {support_id}")
    output.append(f" 🌐 Client IP:          {remote_addr}")
    output.append(f" 🎯 Request Endpoint:   [{method}] {uri}")
    output.append("-" * 70)
    output.append(" 🛡️  ANOMALY DETECTION BREAKDOWN")
    output.append(f"    • Target Parameter: {param_name} ({param_location})")
    output.append(f"    • Raw Input Line:   {line[:80]}..." if len(line) > 80 else f"    • Raw Input Line:   {line}")
    output.append(f"    • Overall Score:    {score:.2f} / 100.00")
    
    # Severity assessment
    if score >= 80:
        severity = "HIGH / CRITICAL ANOMALY (Blocked)"
    elif score >= 50:
        severity = "MEDIUM ANOMALY (Suspicious)"
    else:
        severity = "LOW / BENIGN (Allowed)"
        
    output.append(f"    • Threat Severity:  {severity}")
    output.append("-" * 70)
    output.append(" 🔍 EXPLAINABILITY INDICATORS")
    
    if ntags:
        output.append("    • Threat Classifications (Tags):")
        for tag, tag_vals in ntags.items():
            vals_str = ", ".join(tag_vals) if isinstance(tag_vals, list) else str(tag_vals)
            output.append(f"      - [{tag.upper()}]: {vals_str}")
    else:
        output.append("    • Threat Classifications: None (Structural Unsupervised Anomaly)")

    if keyword_matches:
        output.append(f"    • Triggered Keyword Patterns: {', '.join(keyword_matches)}")

    if scores_array:
        output.append("    • Sub-Score Component Breakdown:")
        for idx, sub_score in enumerate(scores_array, 1):
            output.append(f"      [{idx}] Sub-indicator Weight: {sub_score}")
            
    output.append("=" * 70)
    return "\n".join(output)

def main():
    parser = argparse.ArgumentParser(description="VeriFireWall Explainability Log Parser")
    parser.add_argument("--file", "-f", help="Path to VeriFireWall JSON log file (reads stdin if omitted)")
    args = parser.parse_args()

    if args.file:
        with open(args.file, "r") as f:
            lines = f.readlines()
    else:
        lines = sys.stdin.readlines()

    parsed_count = 0
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            event = json.loads(line)
            print(format_explanation(event))
            parsed_count += 1
        except json.JSONDecodeError:
            continue

    if parsed_count == 0:
        print("No valid VeriFireWall JSON log records found.")

if __name__ == "__main__":
    main()
